### ISSUE TITLE
rsyslog template format not supported by RHEL9. need to modify template

### ISSUE THREAD

**Issue by pratik030** [sous-chefs/rsyslog#231]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

As rsyslog modifying template over default configuration imjournal module failed to load in RHEL9 .

e.g. error imjournal: open() failed for path: '/var/lib/rsyslog/imjournal.state.tmp': Operation not permitted [v8.2310.0-4.el9 try https://www.rsyslog.com/e/2433 ]

## :pancakes: Cookbook version

Version of the cookbook where you are encountering the issue. 9.2.23

## :woman_cook:  Chef-Infra Version

Version of chef-client in your environment. : 9.2.23

## :tophat: Platform details

Operating system distribution and release version. RHEL 9.4

## :police_car: Expected behavior

rysylog service thows error while starting as module not loaded with error operation not permitted. High CPU usage after restart

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by slac-chef-admin** [comment]
https://access.redhat.com/solutions/7070860

Root Cause

This issue happens when using an old configuration file (meant for earlier versions of rsyslog) instead of the default one provided in RHEL 9. The old-style configuration loaded the imjournal module thus:
[Raw](https://access.redhat.com/solutions/7070860#)

$ModLoad imjournal # provides access to the systemd journal
$IMJournalStateFile imjournal.state

Whereas the default way of doing so for RHEL 9 systems is:
[Raw](https://access.redhat.com/solutions/7070860#)

module(load="imjournal"             # provides access to the systemd journal
       UsePid="system" # PID nummber is retrieved as the ID of the process the journal entry originates from
       FileCreateMode="0644" # Set the access permissions for the state file
       StateFile="imjournal.state") # File to store the position in the journal
